version: '2'
services:
  tomcat:
    build: .
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - $PWD/server.xml:/usr/local/tomcat/conf/server.xml
      - $PWD/webapps:/usr/local/tomcat/webapps