version: '3'
services:
  tomcat:
    build: .
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ./server.xml:/usr/local/tomcat/conf/server.xml
      - ./webapps:/usr/local/tomcat/webapps